// O DICIONÁRIO DA AUDITORIA (0288).
//
// O banco registra cada alteração com os nomes TÉCNICOS: `public.clients`,
// `phone`, `journey_phase = planning_center`. Quem lê a Auditoria é o dono, não
// um programador — então aqui cada nome vira português.
//
// Três camadas, da mais certa para a menos certa:
//   1. TABELAS — toda tabela auditada tem rótulo. Preso por teste
//      (`auditoria-alteracoes.test.ts`): tabela nova sem rótulo reprova.
//   2. CAMPOS — os mais comuns têm rótulo escrito à mão; o resto é traduzido
//      palavra a palavra (`PALAVRAS`). Campo raro pode sair meio torto, e o
//      nome técnico fica sempre na dica (title) para tirar a dúvida.
//   3. VALORES — sim/não, dinheiro, data, função, fase... O que não tem
//      tradução aparece como está gravado. Nunca se inventa.

/** `schema.tabela` → nome em português, no singular ("Alterou · Cliente"). */
export const TABELAS: Record<string, string> = {
  // ------------------------------------------------------------- núcleo
  "public.access_idle_settings": "Tempo de inatividade",
  "public.acquirer_rates": "Taxa da adquirente",
  "public.agenda_closure_providers": "Fechamento de agenda — profissional",
  "public.agenda_closure_rooms": "Fechamento de agenda — sala",
  "public.agenda_closures": "Fechamento de agenda",
  "public.agenda_open_day_staff": "Dia extra de agenda — equipe",
  "public.agenda_open_days": "Dia extra de agenda",
  "public.agenda_plan_item_people": "Planejamento da agenda — pessoa",
  "public.agenda_plan_items": "Planejamento da agenda",
  "public.anamnesis_answers": "Resposta de anamnese",
  "public.anamnesis_fills": "Anamnese preenchida",
  "public.anamnesis_questions": "Pergunta de anamnese",
  "public.anamnesis_templates": "Modelo de anamnese",
  "public.appointment_participants": "Participante do agendamento",
  "public.appointment_provider_swaps": "Troca de profissional do agendamento",
  "public.appointments": "Agendamento",
  "public.asset_categories": "Categoria de bem",
  "public.asset_depreciations": "Depreciação de bem",
  "public.attendance_session_outcomes": "Resultado da sessão no atendimento",
  "public.bank_accounts": "Conta bancária",
  "public.bank_statement_imports": "Importação de extrato",
  "public.bank_transactions": "Lançamento do extrato",
  "public.budget_lines": "Meta do orçamento",
  "public.card_acquirer_clinics": "Adquirente — unidade",
  "public.card_acquirers": "Adquirente",
  "public.career_levels": "Nível de carreira",
  "public.chart_of_accounts": "Conta do plano de contas",
  "public.chat_contact_rules": "Regra de contato do chat",
  "public.client_consents": "Consentimento do cliente",
  "public.client_guardians": "Responsável pelo cliente",
  "public.client_shares": "Compartilhamento de cliente",
  "public.clients": "Cliente",
  "public.clinic_agenda_settings": "Configuração da agenda",
  "public.clinic_cost_settings": "Custos da unidade",
  "public.clinic_holiday_decisions": "Decisão sobre feriado",
  "public.clinic_procedure_prices": "Preço do procedimento na unidade",
  "public.clinic_rooms": "Sala / cadeira",
  "public.clinical_anamnesis": "Anamnese clínica",
  "public.clinical_documents": "Documento clínico",
  "public.clinical_evaluations": "Avaliação clínica",
  "public.clinical_guidance": "Orientação clínica",
  "public.clinical_media": "Mídia clínica",
  "public.clinical_notes": "Anotação clínica",
  "public.clinical_progress_notes": "Evolução clínica",
  "public.clinical_request_media": "Arquivo do pedido clínico",
  "public.clinical_requests": "Pedido clínico",
  "public.clinics": "Unidade",
  "public.collection_contacts": "Contato de cobrança",
  "public.commercial_cards": "Cartão do Comercial",
  "public.commercial_followup_attempts": "Tentativa de follow-up",
  "public.commercial_followup_settings": "Configuração de follow-up",
  "public.commercial_presentations": "Apresentação comercial",
  "public.commercial_rules": "Regra comercial",
  "public.commercial_sales": "Venda",
  "public.cost_centers": "Centro de custo",
  "public.direct_sale_items": "Item de venda direta",
  "public.direct_sales": "Venda direta",
  "public.document_templates": "Modelo de documento",
  "public.environments": "Ambiente (treino / sistema)",
  "public.finance_settings": "Configuração do financeiro",
  "public.financial_entries": "Lançamento financeiro",
  "public.fiscal_periods": "Fechamento de competência",
  "public.fixed_assets": "Bem (ativo fixo)",
  "public.inactivity_settings": "Regra de cliente inativo",
  "public.journey_decisions": "Decisão da jornada",
  "public.network_fee_campaigns": "Campanha de taxa da rede",
  "public.network_fee_types": "Tipo de taxa da rede",
  "public.network_fees": "Taxa da rede",
  "public.online_agenda_settings": "Agenda do Comercial (online)",
  "public.payable_approval_rules": "Regra de alçada",
  "public.payable_payments": "Pagamento de conta",
  "public.payable_recurrences": "Conta recorrente",
  "public.payables": "Conta a pagar",
  "public.payment_installments": "Cobrança (parcela)",
  "public.payment_receipts": "Recebimento",
  "public.payment_renegotiations": "Renegociação",
  "public.payout_closings": "Fechamento de repasse",
  "public.permission_matrix": "Permissão",
  "public.plan_cancellations": "Cancelamento de plano",
  "public.plan_negotiation_items": "Item da negociação",
  "public.plan_negotiations": "Negociação",
  "public.plan_quality_reviews": "Revisão de qualidade do plano",
  "public.plan_session_joins": "Atendimento conjunto do plano",
  "public.planning_supplements": "Complemento do planejamento",
  "public.ppr_beneficiaries": "Beneficiário do PPR+",
  "public.ppr_benefit_usages": "Uso de benefício do PPR+",
  "public.ppr_charges": "Cobrança do PPR+",
  "public.ppr_memberships": "Adesão ao PPR+",
  "public.ppr_plan_benefits": "Benefício do plano PPR+",
  "public.ppr_plan_installment_tiers": "Faixa de parcelas do PPR+",
  "public.ppr_plan_perks": "Vantagem do plano PPR+",
  "public.ppr_plans": "Plano PPR+",
  "public.ppr_settings": "Configuração do PPR+",
  "public.ppr_social_points": "Pontos sociais do PPR+",
  "public.procedure_cost_items": "Item de custo do procedimento",
  "public.procedure_costs": "Custo do procedimento",
  "public.procedure_kit_links": "Kit do procedimento",
  "public.procedure_sessions": "Sessão padrão do procedimento",
  "public.procedures": "Procedimento",
  "public.profiles": "Usuário",
  "public.protocol_change_proposals": "Proposta de mudança de protocolo",
  "public.provider_payout_rates": "Tabela de repasse",
  "public.provider_payouts": "Repasse",
  "public.purchase_allocations": "Parte da unidade na compra",
  "public.purchase_order_items": "Item do pedido de compra",
  "public.purchase_orders": "Pedido de compra",
  "public.purchase_quote_items": "Item da cotação",
  "public.purchase_quotes": "Cotação",
  "public.purchase_receipt_items": "Item do recebimento de compra",
  "public.purchase_receipts": "Recebimento de compra",
  "public.purchase_request_items": "Item da requisição de compra",
  "public.purchase_requests": "Requisição de compra",
  "public.purchase_round_items": "Item da rodada de compra",
  "public.purchase_rounds": "Rodada de compra",
  "public.role_unit_access": "Escopo de unidades da função",
  "public.sla_settings": "Prazo (SLA)",
  "public.specialties": "Especialidade",
  "public.split_charges": "Taxa da rede cobrada",
  "public.staff_clinic_schedule": "Horário do Risartano na unidade",
  "public.staff_members": "Risartano",
  "public.stock_count_items": "Item da contagem de estoque",
  "public.stock_counts": "Contagem de estoque",
  "public.stock_items": "Item de estoque",
  "public.stock_kit_items": "Item do kit",
  "public.stock_kits": "Kit",
  "public.stock_movements": "Movimento de estoque",
  "public.stock_purchases": "Compra de estoque",
  "public.supplier_item_links": "Vínculo item × fornecedor",
  "public.suppliers": "Fornecedor",
  "public.system_clinic_access": "Liberação do sistema por unidade",
  "public.system_report_attachments": "Anexo de relato",
  "public.system_report_messages": "Mensagem de relato",
  "public.system_reports": "Relato",
  "public.training_campaign_units": "Turma — unidade",
  "public.training_campaigns": "Turma de certificação",
  "public.training_certifications": "Certificado",
  "public.training_cohort_members": "Grupo do teste coletivo — pessoa",
  "public.training_cohort_roles": "Grupo do teste coletivo — função",
  "public.training_enrollments": "Matrícula na certificação",
  "public.training_requirements": "Meta da certificação",
  "public.training_settings": "Configuração da certificação",
  "public.treatment_plan_option_items": "Item da opção do plano",
  "public.treatment_plan_options": "Opção do plano",
  "public.treatment_plan_stages": "Etapa do plano",
  "public.treatment_plans": "Plano de tratamento",
  "public.treatment_sessions": "Sessão de tratamento",
  "public.user_clinic_roles_all": "Função do usuário na unidade",
  "public.user_environments": "Porta do usuário (treino / sistema)",
  // -------------------------------------------------- Risarte Empresarial
  "empresarial.adhesion_billing": "Cobrança da empresa",
  "empresarial.adhesion_pricing": "Preço da adesão",
  "empresarial.benefit_group_items": "Item do grupo de benefícios",
  "empresarial.benefit_groups": "Grupo de benefícios",
  "empresarial.benefit_usage": "Uso de benefício",
  "empresarial.commercial_lead_activities": "Atividade do lead",
  "empresarial.commercial_leads": "Lead (empresa em negociação)",
  "empresarial.companies": "Empresa",
  "empresarial.company_clinics": "Empresa — unidade",
  "empresarial.company_documents": "Documento (CNPJ) da empresa",
  "empresarial.company_files": "Arquivo da empresa",
  "empresarial.company_inclusion_terms": "Termo de inclusão",
  "empresarial.company_price_tiers": "Faixa de preço da empresa",
  "empresarial.contracts": "Contrato",
  "empresarial.dependents": "Dependente",
  "empresarial.employee_files": "Arquivo do colaborador",
  "empresarial.employees": "Colaborador titular",
  "empresarial.funnel_settings": "Configuração do funil",
  "empresarial.funnel_stage_limits": "Prazo da etapa do funil",
  "empresarial.lead_benefits": "Benefício da proposta",
  "empresarial.lead_clinics": "Lead — unidade",
  "empresarial.lead_closing_reviews": "Revisão de fechamento",
  "empresarial.lead_contact_attempts": "Tentativa de contato",
  "empresarial.lead_dispatches": "Envio da proposta",
  "empresarial.lead_implementation_steps": "Passo da implantação",
  "empresarial.lead_meetings": "Reunião",
  "empresarial.lead_price_tiers": "Faixa de preço da proposta",
  "empresarial.lead_qualification": "Levantamento",
  "empresarial.presentation_templates": "Modelo de apresentação",
  "empresarial.procedure_benefits": "Benefício por procedimento",
  "empresarial.proposal_templates": "Modelo de proposta",
  "empresarial.social_tokens": "Token do Riso+ Social",
  "empresarial.split_rules": "Regra de split",
  "empresarial.welcome_contacts": "Contato de boas-vindas",
  // -------------------------------------------------------- Indica +Risos
  "indica.apuracoes": "Apuração de meta",
  "indica.campanhas": "Campanha do Indica +Risos",
  "indica.catalogo_itens": "Item do catálogo de prêmios",
  "indica.config": "Configuração do Indica +Risos",
  "indica.consentimentos": "Consentimento do Indica +Risos",
  "indica.embaixadores": "Embaixador",
  "indica.indicacoes": "Indicação",
  "indica.metas_equipe": "Meta da equipe",
  "indica.niveis": "Nível de Embaixador",
  "indica.parceiros": "Parceiro",
  "indica.pedidos_indicacao": "Pedido de indicação",
  "indica.pontos_lancamentos": "Lançamento de Riso Coins",
  "indica.resgates": "Resgate",
};

/** As três áreas, para o filtro e para o selo ao lado do registro. */
export const AREAS: Record<string, string> = {
  public: "riSZon",
  empresarial: "Empresarial",
  indica: "Indica +Risos",
};

/** Campos com rótulo escrito à mão (os que mais aparecem). */
export const CAMPOS: Record<string, string> = {
  id: "Identificador",
  code: "Código",
  codigo: "Código",
  name: "Nome",
  nome: "Nome",
  full_name: "Nome completo",
  preferred_name: "Nome preferido",
  legal_name: "Razão social",
  trade_name: "Nome fantasia",
  title: "Título",
  label: "Rótulo",
  description: "Descrição",
  descricao: "Descrição",
  notes: "Observações",
  note: "Observação",
  body: "Texto",
  content: "Conteúdo",
  cpf: "CPF",
  cnpj: "CNPJ",
  no_cpf: "Sem CPF",
  birth_date: "Data de nascimento",
  gender: "Gênero",
  marital_status: "Estado civil",
  phone: "Telefone",
  whatsapp: "WhatsApp",
  email: "E-mail",
  address: "Endereço",
  address_number: "Número",
  complement: "Complemento",
  neighborhood: "Bairro",
  city: "Cidade",
  state: "Estado",
  zip_code: "CEP",
  status: "Situação",
  kind: "Tipo",
  type: "Tipo",
  tipo: "Tipo",
  category: "Categoria",
  scope: "Abrangência",
  escopo: "Abrangência",
  role: "Função",
  role_title: "Cargo",
  unit_scope: "Escopo de unidades",
  is_active: "Ativo",
  active: "Ativo",
  ativo: "Ativo",
  allowed: "Permitido",
  is_admin_master: "Admin Master",
  is_owner: "Dono",
  is_default: "Padrão",
  is_primary: "Principal",
  is_online: "Online",
  sort_order: "Ordem",
  seq: "Sequência",
  clinic_id: "Unidade",
  unidade_id: "Unidade",
  preferred_clinic_id: "Unidade de preferência",
  origin_clinic_id: "Unidade de origem",
  main_clinic_id: "Unidade principal",
  client_id: "Cliente",
  cliente_id: "Cliente",
  user_id: "Usuário",
  staff_member_id: "Risartano",
  provider_user_id: "Profissional",
  provider_id: "Profissional",
  consultant_id: "Consultor",
  author_id: "Autor",
  company_id: "Empresa",
  employee_id: "Colaborador",
  dependent_id: "Dependente",
  lead_id: "Lead",
  supplier_id: "Fornecedor",
  procedure_id: "Procedimento",
  procedure_name: "Procedimento",
  plan_id: "Plano",
  option_id: "Opção do plano",
  item_id: "Item",
  appointment_id: "Agendamento",
  negotiation_id: "Negociação",
  direct_sale_id: "Venda direta",
  session_id: "Sessão",
  room_id: "Sala / cadeira",
  acquirer_id: "Adquirente",
  cost_center_id: "Centro de custo",
  account_code: "Conta contábil",
  membership_id: "Adesão",
  campaign_id: "Campanha",
  campanha_id: "Campanha",
  embaixador_id: "Embaixador",
  parceiro_id: "Parceiro",
  career_level_id: "Nível de carreira",
  created_at: "Criado em",
  criado_em: "Criado em",
  created_by: "Criado por",
  criado_por: "Criado por",
  updated_at: "Atualizado em",
  updated_by: "Atualizado por",
  closed_at: "Fechado em",
  closed_by: "Fechado por",
  cancelled_at: "Cancelado em",
  cancelled_by: "Cancelado por",
  cancel_reason: "Motivo do cancelamento",
  reason: "Motivo",
  motivo: "Motivo",
  reviewed_at: "Avaliado em",
  reviewed_by: "Avaliado por",
  review_notes: "Considerações da avaliação",
  approved_at: "Aprovado em",
  approved_by: "Aprovado por",
  submitted_at: "Enviado para aprovação em",
  sent_at: "Enviado em",
  done_at: "Concluído em",
  done_by: "Concluído por",
  paid_at: "Pago em",
  paid_by: "Baixa feita por",
  starts_at: "Início",
  ends_at: "Fim",
  due_date: "Vencimento",
  due_day: "Dia do vencimento",
  accrual_date: "Data de competência",
  cash_date: "Data do caixa",
  reference_month: "Mês de referência",
  period_month: "Mês",
  amount_cents: "Valor",
  total_cents: "Total",
  final_cents: "Valor final",
  price_cents: "Preço",
  unit_cents: "Valor unitário",
  discount_cents: "Desconto",
  discount_percent: "Desconto (%)",
  paid_amount_cents: "Valor pago",
  paid_fee_cents: "Multa paga",
  paid_interest_cents: "Juros pagos",
  default_price_cents: "Preço padrão",
  min_price_cents: "Preço mínimo",
  max_price_cents: "Preço máximo",
  commission_percent: "Comissão (%)",
  commission_fixed_cents: "Comissão fixa",
  late_fee_percent: "Multa (%)",
  monthly_interest_percent: "Juros ao mês (%)",
  grace_days: "Carência (dias)",
  grace_period_days: "Carência (dias)",
  grace_period_months: "Carência (meses)",
  payment_method: "Meio de pagamento",
  max_installments: "Máximo de parcelas",
  installments: "Parcelas",
  quantity: "Quantidade",
  percent: "Percentual",
  journey_phase: "Fase da jornada",
  journey_status: "Sub-status da jornada",
  phase_entered_at: "Entrou na fase em",
  methodology_pillar: "Pilar",
  pillar: "Pilar",
  attendance: "Atendimento",
  checked_in_at: "Check-in em",
  checked_in_by: "Check-in feito por",
  called_at: "Chamado em",
  called_by: "Chamado por",
  needs_reschedule: "Precisa remarcar",
  diagnosis: "Diagnóstico",
  objectives: "Objetivos",
  planning_notes: "Anotações do planejamento",
  lifecycle: "Situação do plano",
  specialty: "Especialidade",
  specialties: "Especialidades",
  tuss_code: "Código TUSS",
  estimated_minutes: "Tempo estimado (min)",
  planned_minutes: "Tempo previsto (min)",
  actual_minutes: "Tempo realizado (min)",
  session_index: "Número da sessão",
  session_total: "Total de sessões",
  planned_date: "Data prevista",
  executed_by: "Executado por",
  contract_signed: "Contrato assinado",
  contract_signed_at: "Contrato assinado em",
  contract_signed_by: "Assinatura registrada por",
  payment_confirmed: "Pagamento confirmado",
  payment_confirmed_at: "Pagamento confirmado em",
  payment_confirmed_by: "Pagamento confirmado por",
  payment_issued: "Cobrança emitida",
  payment_issued_at: "Cobrança emitida em",
  payment_issued_by: "Cobrança emitida por",
  storage_path: "Arquivo",
  file_name: "Nome do arquivo",
  photo_path: "Foto",
  size_bytes: "Tamanho",
  uploaded_by: "Enviado por",
  anonymized_at: "Anonimizado em",
  registration_complete: "Cadastro completo",
  idle_minutes: "Minutos sem uso",
  papel: "Função",
  capability: "Permissão",
  invoice_number: "Número da nota",
  document_number: "Número do documento",
  reference: "Referência",
  outcome: "Resultado",
  channel: "Canal",
  canal: "Canal",
  stage: "Etapa",
  relationship: "Parentesco",
  contracted_holders: "Titulares contratados",
  contracted_dependents: "Dependentes contratados",
  fixed_monthly_cents: "Mensalidade fixa",
  holder_fee_cents: "Valor por titular",
  dependent_fee_cents: "Valor por dependente",
  responsible_name: "Responsável",
  responsible_cpf: "CPF do responsável",
  responsible_email: "E-mail do responsável",
  responsible_phone: "Telefone do responsável",
  responsible_role: "Cargo do responsável",
  indicado_nome: "Nome do indicado",
  indicado_telefone: "Telefone do indicado",
  indicado_cpf: "CPF do indicado",
  indicado_email: "E-mail do indicado",
  valor_centavos: "Valor",
  valor_fechado_centavos: "Valor fechado",
  riso_coins: "Riso Coins",
};

/**
 * Palavra a palavra, para o campo que não tem rótulo próprio.
 * `expected_settlement_date` → "previsto liquidação data". Sai torto, mas
 * legível — e o nome técnico fica na dica. Sufixos que só dizem o TIPO
 * (`_cents`, `_id`) somem: o valor já aparece formatado.
 */
export const PALAVRAS: Record<string, string> = {
  access: "acesso", account: "conta", accrual: "competência", acquirer: "adquirente",
  active: "ativo", actual: "realizado", added: "adicionado", address: "endereço",
  adhesion: "adesão", adhesions: "adesões", agenda: "agenda", agreements: "acordos",
  alert: "alerta", allowed: "permitido", amount: "valor", answer: "resposta",
  applied: "aplicado", approval: "aprovação", approved: "aprovado", asset: "bem",
  at: "em", attendance: "atendimento", authorization: "autorização",
  authorized: "autorizado", auto: "automático", bank: "banco", basis: "base",
  benefit: "benefício", billing: "cobrança", boleto: "boleto", by: "por",
  cancel: "cancelamento", cancelled: "cancelado", card: "cartão", cash: "caixa",
  category: "categoria", charge: "cobrança", client: "cliente", clinic: "unidade",
  clinics: "unidades", close: "fechamento", closed: "fechado", closure: "fechamento",
  commercial: "comercial", company: "empresa", confirmed: "confirmado",
  contact: "contato", contacted: "contatado", contract: "contrato",
  contracted: "contratado", cost: "custo", count: "quantidade", created: "criado",
  date: "data", day: "dia", days: "dias", decided: "decidido", default: "padrão",
  deleted: "excluído", dependent: "dependente", dependents: "dependentes",
  direct: "direta", discount: "desconto", document: "documento", done: "concluído",
  down: "entrada", due: "vencimento", employee: "colaborador", end: "fim",
  ends: "fim", estimated: "estimado", evaluation: "avaliação", excess: "excedente",
  expected: "previsto", expires: "vence", extra: "extra", family: "família",
  fee: "taxa", file: "arquivo", final: "final", first: "primeiro", fixed: "fixo",
  follow: "acompanhamento", for: "para", from: "de", granted: "concedido",
  grace: "carência", holder: "titular", holders: "titulares", import: "importação",
  installment: "parcela", installments: "parcelas", interest: "juros",
  invoice: "nota", is: "", issue: "emissão", issued: "emitido", item: "item",
  items: "itens", joined: "entrou", key: "chave", kit: "kit", last: "último",
  late: "atraso", lead: "lead", left: "saiu", level: "nível", limit: "limite",
  locked: "travado", lot: "lote", main: "principal", max: "máximo",
  message: "mensagem", method: "meio", methods: "meios", min: "mínimo",
  minutes: "minutos", mode: "modo", model: "modelo", month: "mês",
  monthly: "mensal", months: "meses", name: "nome", negotiation: "negociação",
  network: "rede", notes: "observações", number: "número", open: "aberto",
  option: "opção", order: "ordem", origin: "origem", original: "original",
  paid: "pago", payable: "conta a pagar", payment: "pagamento", payout: "repasse",
  percent: "(%)", period: "período", phone: "telefone", plan: "plano",
  planned: "previsto", planner: "planner", price: "preço", procedure: "procedimento",
  program: "programa", provider: "profissional", purchase: "compra",
  quality: "qualidade", quantity: "quantidade", reason: "motivo",
  receipt: "recebimento", received: "recebido", recorded: "registrado",
  recurrence: "recorrência", reference: "referência", registration: "cadastro",
  renegotiation: "renegociação", reopen: "reabertura", reopened: "reaberto",
  report: "relato", request: "pedido", requested: "pedido", requires: "exige",
  resolved: "resolvido", return: "retorno", returned: "devolvido",
  reversal: "estorno", reversed: "estornado", review: "avaliação",
  reviewed: "avaliado", revoked: "revogado", room: "sala", round: "rodada",
  sale: "venda", schedule: "horário", section: "seção", sections: "seções",
  sent: "enviado", session: "sessão", settlement: "liquidação", signed: "assinado",
  size: "tamanho", source: "origem", special: "especiais", stage: "etapa",
  start: "início", started: "iniciado", starts: "início", stock: "estoque",
  subsidy: "subsídio", subtotal: "subtotal", summary: "resumo", supplier: "fornecedor",
  target: "alvo", template: "modelo", time: "horário", to: "até", total: "total",
  treatment: "tratamento", unit: "unidade", units: "unidades", updated: "atualizado",
  usage: "uso", used: "usado", user: "usuário", valid: "válido", value: "valor",
  was: "estava", weekdays: "dias da semana", when: "quando", year: "ano",
  overdue: "em atraso", status: "situação", type: "tipo", kind: "tipo", code: "código",
};

/** Campos que são dinheiro em centavos (além dos terminados em `_cents`). */
export const SUFIXOS_DE_DINHEIRO = ["_cents", "_centavos"];
