// Rótulos pt-BR para a tela de Auditoria (H4.1 Lote 3). A trilha `audit_logs`
// guarda ação e tipo de registro como códigos em inglês; aqui viram texto.

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  login: "Entrou no sistema",
  logout: "Saiu do sistema",
  create: "Cadastrou",
  update: "Alterou",
  view: "Consultou",
  delete: "Excluiu",
  anonymize: "Anonimizou",
  export: "Exportou",
};

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action;
}

/** Ações oferecidas no filtro (as mais comuns). */
export const AUDIT_ACTION_OPTIONS: { value: string; label: string }[] = [
  { value: "login", label: "Entrou no sistema" },
  { value: "logout", label: "Saiu do sistema" },
  { value: "create", label: "Cadastrou" },
  { value: "update", label: "Alterou" },
  { value: "view", label: "Consultou" },
  { value: "delete", label: "Excluiu" },
  { value: "export", label: "Exportou" },
  { value: "anonymize", label: "Anonimizou" },
];

// ⚠️ TODO tipo de registro que o sistema grava na trilha tem rótulo aqui. A
// régua `auditoria-alteracoes.test.ts` varre o código atrás de cada
// `entityType: "..."` e reprova o que ficar sem — em 09/10/2026 eram 205
// tipos e só 16 tinham nome; o resto aparecia em inglês na tela do dono.
export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  session: "Acesso",
  access_idle_settings: "Tempo de inatividade",
  audit_activity_report: "Relatório de atividade (Auditoria)",
  // ------------------------------------------------ cliente e prontuário
  client: "Cliente",
  client_consent: "Consentimento do cliente",
  client_phase: "Fase do cliente",
  client_journey: "Jornada do cliente",
  client_pillar: "Pilar do cliente",
  client_status: "Situação do cliente",
  client_transfer: "Transferência de cliente",
  client_share: "Compartilhamento",
  consent: "Consentimento",
  anamnesis: "Anamnese",
  anamnesis_fill: "Anamnese preenchida",
  anamnesis_question: "Pergunta de anamnese",
  anamnesis_template: "Modelo de anamnese",
  clinical_anamnesis: "Anamnese clínica",
  clinical_document: "Documento clínico",
  clinical_evaluation: "Avaliação clínica",
  clinical_guidance: "Orientação clínica",
  clinical_media: "Mídia clínica",
  clinical_note: "Anotação clínica",
  clinical_progress_note: "Evolução clínica",
  clinical_request: "Pedido clínico",
  document_template: "Modelo de documento",
  // ------------------------------------------------------- plano e agenda
  treatment_plan: "Plano de tratamento",
  plan_option: "Opção do plano",
  treatment_plan_option: "Opção do plano",
  planning_supplement: "Complemento do planejamento",
  plan_quality_review: "Revisão de qualidade do plano",
  protocol_change_proposal: "Proposta de mudança de protocolo",
  treatment_session: "Sessão de tratamento",
  treatment_sessions: "Sessões de tratamento",
  item_scheduling_request: "Pedido de agendamento do item",
  quality_scheduling_request: "Pedido de agendamento da qualidade",
  appointment: "Agendamento",
  agenda_closure: "Fechamento de agenda",
  agenda_open_day: "Dia extra de agenda",
  agenda_plan_item: "Planejamento da agenda",
  agenda_plan_item_network: "Planejamento da agenda (rede)",
  agenda_settings: "Configuração da agenda",
  agenda_settings_network: "Configuração da agenda (rede)",
  online_agenda_settings: "Agenda do Comercial (online)",
  // ------------------------------------------------------------ comercial
  commercial_cockpit: "Cockpit do Comercial",
  commercial_dashboard: "Painel do Comercial",
  commercial_kanban: "Quadro do Comercial",
  commercial_card: "Cartão do Comercial",
  commercial_presentation: "Apresentação comercial",
  presentation: "Apresentação",
  commercial_rule: "Regra comercial",
  commercial_rule_removed: "Regra comercial (removida)",
  commercial_followup_settings: "Configuração de follow-up",
  commercial_followup_settings_removed: "Configuração de follow-up (removida)",
  commercial_followup_attempt: "Tentativa de follow-up",
  commercial_followup_start: "Início de follow-up",
  commercial_sale: "Venda",
  plan_negotiation: "Negociação",
  plan_negotiation_accept: "Negociação aceita",
  plan_negotiation_review: "Negociação avaliada pela unidade",
  negotiation_cancel: "Negociação cancelada",
  plan_cancellation: "Cancelamento de plano",
  plan_cancellation_apply: "Cancelamento de plano efetivado",
  plan_cancellation_sign: "Termo de cancelamento assinado",
  direct_sale: "Venda direta",
  direct_sale_cancel: "Venda direta cancelada",
  direct_sale_close: "Venda direta fechada",
  direct_sale_conditions: "Condições da venda direta",
  direct_sale_page: "Tela de venda direta",
  // ----------------------------------------------------------- financeiro
  payment_schedule: "Parcelas da venda",
  payment_receipt: "Recebimento",
  payment_receipt_reversal: "Estorno de recebimento",
  payment_renegotiation: "Renegociação",
  renegotiation_close: "Renegociação concluída",
  collection_contact: "Contato de cobrança",
  boleto_issue: "Emissão de boleto",
  payable: "Conta a pagar",
  payable_approval: "Autorização de conta a pagar",
  payable_approval_rule: "Regra de alçada",
  payable_cancel: "Conta a pagar cancelada",
  payable_payment: "Pagamento de conta",
  payable_payment_reversal: "Estorno de pagamento de conta",
  payable_recurrence: "Conta recorrente",
  bank_account: "Conta bancária",
  bank_reconciliation: "Conciliação bancária",
  bank_reconciliation_undo: "Conciliação desfeita",
  bank_statement_import: "Importação de extrato",
  bank_statement_import_undo: "Importação de extrato desfeita",
  bank_transaction_ignore: "Lançamento do extrato ignorado",
  entry_from_bank: "Lançamento criado pelo extrato",
  card_acquirer: "Adquirente",
  acquirer_rate: "Taxa da adquirente",
  acquirer_rate_close: "Taxa da adquirente (vigência encerrada)",
  acquirer_rate_delete: "Taxa da adquirente (excluída)",
  chart_account: "Conta do plano de contas",
  cost_center: "Centro de custo",
  budget_line: "Meta do orçamento",
  budget_copy: "Orçamento copiado do ano anterior",
  budget_fill: "Orçamento sugerido pela média",
  finance_settings: "Configuração do financeiro",
  finance_alert_settings: "Limites dos alertas do financeiro",
  fiscal_period_close: "Competência fechada",
  fiscal_period_reopen: "Competência reaberta",
  fixed_asset: "Bem (ativo fixo)",
  asset_depreciation: "Depreciação de bens",
  payout_closing: "Fechamento de repasse",
  payout_rate: "Tabela de repasse",
  network_fee: "Taxa da rede",
  network_fee_clear: "Taxa da rede (acordo removido)",
  network_fee_type: "Tipo de taxa da rede",
  network_fee_type_delete: "Tipo de taxa da rede (excluído)",
  network_fee_campaign: "Campanha de taxa da rede",
  network_fee_campaign_delete: "Campanha de taxa da rede (excluída)",
  clinic_cost_settings: "Custos da unidade",
  clinic_ownership: "Tipo de unidade (própria / franqueada)",
  // ---------------------------------------------- procedimentos e estoque
  procedure: "Procedimento",
  procedure_cost: "Custo do procedimento",
  procedure_price_from_simulator: "Preço definido pelo precificador",
  procedure_sessions: "Sessões padrão do procedimento",
  specialty: "Especialidade",
  stock_item: "Item de estoque",
  stock_kit: "Kit",
  stock_movement: "Movimento de estoque",
  stock_open_package: "Embalagem enviada para uso",
  stock_count: "Contagem de estoque",
  stock_purchase: "Compra de estoque",
  stock_purchase_nfe: "Compra de estoque (nota fiscal)",
  supplier: "Fornecedor",
  purchase_request: "Requisição de compra",
  purchase_request_send: "Requisição de compra enviada",
  purchase_round: "Rodada de compra",
  purchase_round_award: "Fornecedor escolhido na rodada",
  purchase_round_close: "Rodada de compra fechada",
  purchase_allocation: "Parte da unidade na compra",
  purchase_orders: "Pedidos de compra",
  purchase_receipt: "Recebimento de compra",
  // -------------------------------------------------- pessoas e permissão
  staff_member: "Risartano",
  staff_clinic_schedule: "Horário do Risartano na unidade",
  career_level: "Nível de carreira",
  provider_career_level: "Nível de carreira do profissional",
  user: "Usuário",
  user_clinic_roles: "Acesso (função)",
  user_environments: "Portas do usuário (treino / sistema)",
  environments: "Ambientes (treino / sistema)",
  permission_matrix: "Permissões",
  system_clinic_access: "Liberação do sistema por unidade",
  chat_contact_rule: "Regra de contato do chat",
  clinic: "Clínica",
  clinic_room: "Sala / cadeira",
  sla_settings: "Prazos (SLA)",
  inactivity_settings: "Regra de cliente inativo",
  mirror_state: "Espelho do treino",
  system_reports: "Relato",
  system_report_attachments: "Anexo de relato",
  training_campaigns: "Turma de certificação",
  training_enrollments: "Matrícula na certificação",
  training_requirements: "Metas da certificação",
  training_settings: "Configuração da certificação",
  // ----------------------------------------------------------------- PPR+
  ppr_plan: "Plano PPR+",
  ppr_plan_benefit: "Benefício do plano PPR+",
  ppr_membership: "Adesão ao PPR+",
  ppr_membership_cancel: "Adesão ao PPR+ cancelada",
  ppr_charges: "Cobranças do PPR+",
  ppr_settings: "Configuração do PPR+",
  ppr_dashboard: "Painel do PPR+",
  // -------------------------------------------------- Risarte Empresarial
  empresarial_company: "Empresa (Empresarial)",
  empresarial_company_document: "Documento da empresa",
  empresarial_company_file: "Arquivo da empresa",
  empresarial_company_report: "Relatório da empresa",
  empresarial_company_sheet: "Ficha da empresa",
  empresarial_contract: "Contrato (Empresarial)",
  empresarial_inclusion_term: "Termo de inclusão",
  empresarial_employee: "Colaborador (Empresarial)",
  empresarial_employee_file: "Arquivo do colaborador",
  empresarial_employee_import: "Importação de colaboradores",
  empresarial_dependent: "Dependente (Empresarial)",
  empresarial_billing: "Cobrança da empresa",
  empresarial_adhesion_pricing: "Preço da adesão (Empresarial)",
  empresarial_split_rules: "Regras de split (Empresarial)",
  empresarial_benefit_group: "Grupo de benefícios",
  empresarial_benefit_group_excluido: "Grupo de benefícios (excluído)",
  empresarial_benefits_report: "Relatório de benefícios",
  empresarial_procedure_benefit: "Benefício por procedimento",
  empresarial_social_token: "Token do Riso+ Social",
  empresarial_retention: "Retenção (Empresarial)",
  empresarial_lead: "Lead (Empresarial)",
  empresarial_lead_qualification: "Levantamento (Empresarial)",
  empresarial_lead_benefits: "Benefícios da proposta",
  empresarial_lead_meeting: "Reunião (Empresarial)",
  empresarial_lead_dispatch: "Envio da proposta",
  empresarial_lead_closing_review: "Revisão de fechamento",
  empresarial_proposal: "Proposta (Empresarial)",
  empresarial_proposal_template: "Modelo de proposta",
  empresarial_welcome_contact: "Contato de boas-vindas",
  empresarial_welcome_list: "Lista de boas-vindas",
  // -------------------------------------------------------- Indica +Risos
  indica_indicacao: "Indicação",
  indica_embaixador: "Embaixador",
  indica_embaixador_status: "Situação do Embaixador",
  indica_link_portal: "Link do portal do Embaixador",
  indica_parceiro: "Parceiro (Indica +Risos)",
  indica_campanha: "Campanha (Indica +Risos)",
  indica_catalogo_item: "Item do catálogo de prêmios",
  indica_nivel: "Nível de Embaixador",
  indica_meta: "Meta da equipe (Indica +Risos)",
  indica_apuracao: "Apuração de meta (Indica +Risos)",
  indica_config: "Configuração do Indica +Risos",
  indica_relatorio: "Relatório do Indica +Risos",
  indica_ajuste: "Ajuste manual de Riso Coins",
  indica_alerta: "Alerta antifraude (Indica +Risos)",
  indica_resgate: "Resgate (Indica +Risos)",
  indica_voucher: "Voucher (Indica +Risos)",
};

export function auditEntityLabel(entityType: string): string {
  return AUDIT_ENTITY_LABELS[entityType] ?? entityType;
}

/** Tipos de registro oferecidos no filtro — todos, em ordem alfabética. */
export const AUDIT_ENTITY_OPTIONS: { value: string; label: string }[] =
  Object.entries(AUDIT_ENTITY_LABELS)
    .map(([value, label]) => ({ value, label }))
    .sort((a, b) => a.label.localeCompare(b.label, "pt-BR"));
